image: rust:latest

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - $CARGO_HOME

default:
  before_script:
    - rustc --version
    - cargo --version
    - make rustup
    - make check

stages:
  - build
  - test

lint:
  stage: build
  script:
    - make lint

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - build
    expire_in: 14 days

test-contract:
  stage: test
  script:
    - make test-contract
  artifacts:
    paths:
      - target
    expire_in: 1 days
